"""add debrief columns

Revision ID: 765c8404f6be
Revises: bd49d6e7a1fc
Create Date: 2026-04-20 14:56:08.000096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765c8404f6be'
down_revision: Union[str, None] = 'bd49d6e7a1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('debrief_d1', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('debrief_d2', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('debrief_d3', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('debrief_d4', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('debrief_d5', sa.Text(), nullable=True))
    op.add_column('participants', sa.Column('debrief_d6', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'debrief_d6')
    op.drop_column('participants', 'debrief_d5')
    op.drop_column('participants', 'debrief_d4')
    op.drop_column('participants', 'debrief_d3')
    op.drop_column('participants', 'debrief_d2')
    op.drop_column('participants', 'debrief_d1')
    # ### end Alembic commands ###
