"""initial schema

Revision ID: d585d72243d7
Revises: 
Create Date: 2026-04-20 16:39:14.126980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd585d72243d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_code', sa.String(length=12), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('warmup_w1', sa.Text(), nullable=True),
    sa.Column('warmup_w2', sa.Text(), nullable=True),
    sa.Column('warmup_w3', sa.Text(), nullable=True),
    sa.Column('warmup_w4', sa.Text(), nullable=True),
    sa.Column('debrief_d1', sa.Text(), nullable=True),
    sa.Column('debrief_d2', sa.Text(), nullable=True),
    sa.Column('debrief_d3', sa.Text(), nullable=True),
    sa.Column('debrief_d4', sa.Text(), nullable=True),
    sa.Column('debrief_d5', sa.Text(), nullable=True),
    sa.Column('debrief_d6', sa.Text(), nullable=True),
    sa.Column('scenario_order', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_session_code'), 'participants', ['session_code'], unique=True)
    op.create_table('responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('swiped_right', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('variant_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_index(op.f('ix_participants_session_code'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
